trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@4
    inputs:
      gradleWrapperFile: "gradlew"
      tasks: "build"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      javaHomeOption: "JDKVersion"
      sonarQubeRunAnalysis: false
      checkStyleRunAnalysis: false
      spotBugsAnalysis: false
