trigger:
  - main

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

stages:
  - stage: Build
    jobs:
      - job: gradleBuild
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Cache@2
            inputs:
              key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts' # Swap build.gradle.kts for build.gradle when using Groovy
              restoreKeys:
                | # The fallback keys if the primary key fails (Optional)
                gradle | "$(Agent.OS)"
                gradle
              path: $(GRADLE_USER_HOME)
            displayName: Configure gradle caching

          - task: Gradle@4
            inputs:
              gradleWrapperFile: "gradlew"
              tasks: "build"
              options: "--build-cache"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: "JDKVersion"
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: false
              spotBugsAnalysis: false

          - script: |
              # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
              ./gradlew --stop
            displayName: Gradlew stop

          - task: CopyFiles@2
            displayName: "Copy Files to artifact staging directory"
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: "**/build/libs/*SNAPSHOT.jar"
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: webapp

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: AzureDeployment
        environment: production
        strategy:
          runOnce:
            deploy:
              pool:
                vmImage: ubuntu-latest
              steps:
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy: spring-hello-vsc-pf2128373"
                  inputs:
                    azureSubscription: f503da24-ed17-44cd-9ad1-38d110a621f3
                    appType: webAppLinux
                    appName: spring-hello-vsc-pf2128373
                    package: "$(Pipeline.Workspace)/webapp/build/libs/*.jar"
