trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: gradleBuild
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Gradle@4
            inputs:
              gradleWrapperFile: "gradlew"
              tasks: "build"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: "JDKVersion"
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: false
              spotBugsAnalysis: false

          - task: CopyFiles@2
            displayName: "Copy Files to artifact staging directory"
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: "**/build/libs/*.jar"
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: webapp

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: AzureDeployment
        strategy:
          runOnce:
            deploy:
              pool:
                vmImage: ubuntu-latest
              steps:
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy: spring-hello-vsc-pf2128373"
                  inputs:
                    azureSubscription: f503da24-ed17-44cd-9ad1-38d110a621f3
                    appType: webAppLinux
                    appName: spring-hello-vsc-pf2128373
                    package: "$(Pipeline.Workspace)/drop/**/target/*.jar"